name: Setup
description: Setup environment

runs:
  using: composite
  steps:
    # setup
    - uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3.6.3

    # install dependencies
    - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: |
          ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
    - run: bun install --frozen-lockfile
      shell: bash