name: Setup
description: Setup environment

runs:
  using: composite
  steps:
    # setup
    - uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3.6.3

    # install dependencies
    - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: |
          ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
    - run: bun install --frozen-lockfile
      shell: bash