/**
 * Diagram機能で使用するアイコンの一覧
 */

import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowRight,
  BatteryWarning,
  BookOpen,
  Bot,
  Box,
  Brain,
  BrainCircuit,
  Building,
  Check,
  CheckCircle,
  CheckSquare,
  Clock,
  Code2,
  Copy,
  Cpu,
  Database,
  Eye,
  EyeOff,
  Feather,
  FileCode,
  FileSearch,
  FileText,
  Flag,
  Frown,
  GitMerge,
  Hammer,
  Heart,
  HelpCircle,
  History,
  Languages,
  Layers,
  Layout,
  LayoutDashboard,
  LayoutTemplate,
  Lightbulb,
  Lock,
  type LucideIcon,
  Map as MapIcon,
  MessageCircle,
  MessageSquare,
  MessageSquareX,
  Microscope,
  Minimize2,
  MousePointer,
  Pencil,
  PenTool,
  PieChart,
  Puzzle,
  RefreshCcw,
  Rocket,
  Scale,
  Scan,
  Search,
  Server,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Target,
  Terminal,
  TrendingDown,
  TrendingUp,
  Users,
  UserX,
  Wrench,
  X,
  XCircle,
  Zap,
  ZapOff,
} from 'lucide-react';

/**
 * 使用可能なアイコン名の配列(真実の源)
 * Zodスキーマ生成で直接使用可能なタプル型
 */
export const ICON_NAMES = [
  'activity',
  'alert',
  'alertCircle',
  'alertTriangle',
  'arrow',
  'arrowDown',
  'arrowRight',
  'batteryWarning',
  'bookOpen',
  'bot',
  'box',
  'brain',
  'brainCircuit',
  'building',
  'check',
  'checkCircle',
  'checkSquare',
  'clock',
  'code2',
  'copy',
  'cpu',
  'database',
  'eye',
  'eyeOff',
  'feather',
  'fileCode',
  'fileSearch',
  'fileText',
  'flag',
  'frown',
  'gitMerge',
  'hammer',
  'heart',
  'help',
  'history',
  'languages',
  'layers',
  'layout',
  'layoutDashboard',
  'layoutTemplate',
  'lightbulb',
  'lock',
  'map',
  'message',
  'messageSquare',
  'messageSquareX',
  'microscope',
  'minimize2',
  'mousePointer',
  'pen',
  'pencil',
  'pieChart',
  'puzzle',
  'refreshCcw',
  'rocket',
  'scale',
  'scan',
  'search',
  'server',
  'settings',
  'shieldAlert',
  'shieldCheck',
  'smartphone',
  'sparkles',
  'target',
  'terminal',
  'trendingDown',
  'trendingUp',
  'userX',
  'users',
  'wrench',
  'x',
  'xCircle',
  'zap',
  'zapOff',
] as const;

/**
 * アイコン名の型定義(ICON_NAMESから派生)
 */
export type IconName = (typeof ICON_NAMES)[number];

/**
 * アイコン名とLucideコンポーネントのマッピング
 * ICON_NAMESの型に基づいて型安全性を保証
 */
export const ICON_MAP: Record<IconName, LucideIcon> = {
  activity: Activity,
  alert: AlertCircle,
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  arrow: ArrowDown,
  arrowDown: ArrowDown,
  arrowRight: ArrowRight,
  batteryWarning: BatteryWarning,
  bookOpen: BookOpen,
  bot: Bot,
  box: Box,
  brain: Brain,
  brainCircuit: BrainCircuit,
  building: Building,
  check: Check,
  checkCircle: CheckCircle,
  checkSquare: CheckSquare,
  clock: Clock,
  code2: Code2,
  copy: Copy,
  cpu: Cpu,
  database: Database,
  eye: Eye,
  eyeOff: EyeOff,
  feather: Feather,
  fileCode: FileCode,
  fileSearch: FileSearch,
  fileText: FileText,
  flag: Flag,
  frown: Frown,
  gitMerge: GitMerge,
  hammer: Hammer,
  heart: Heart,
  help: HelpCircle,
  history: History,
  languages: Languages,
  layers: Layers,
  layout: Layout,
  layoutDashboard: LayoutDashboard,
  layoutTemplate: LayoutTemplate,
  lightbulb: Lightbulb,
  lock: Lock,
  map: MapIcon,
  message: MessageCircle,
  messageSquare: MessageSquare,
  messageSquareX: MessageSquareX,
  microscope: Microscope,
  minimize2: Minimize2,
  mousePointer: MousePointer,
  pen: PenTool,
  pencil: Pencil,
  pieChart: PieChart,
  puzzle: Puzzle,
  refreshCcw: RefreshCcw,
  rocket: Rocket,
  scale: Scale,
  scan: Scan,
  search: Search,
  server: Server,
  settings: Settings,
  shieldAlert: ShieldAlert,
  shieldCheck: ShieldCheck,
  smartphone: Smartphone,
  sparkles: Sparkles,
  target: Target,
  terminal: Terminal,
  trendingDown: TrendingDown,
  trendingUp: TrendingUp,
  users: Users,
  userX: UserX,
  wrench: Wrench,
  x: X,
  xCircle: XCircle,
  zap: Zap,
  zapOff: ZapOff,
};
